namespace Econolite.Asn1J2735.J2735;

public enum SegmentAttribute
{
    Reserved = 0,
    DoNotBlock = 1,
    WhiteLine = 2,
    MergingLaneLeft = 3,
    MergingLaneRight = 4,
    CurbOnLeft = 5,
    CurbOnRight = 6,
    LoadingzoneOnLeft = 7,
    LoadingzoneOnRight = 8,
    TurnOutPointOnLeft = 9,
    TurnOutPointOnRight = 10,
    AdjacentParkingOnLeft = 11,
    AdjacentParkingOnRight = 12,
    AdjacentBikeLaneOnLeft = 13,
    AdjacentBikeLaneOnRight = 14,
    SharedBikeLane = 15,
    BikeBoxInFront = 16,
    TransitStopOnLeft = 17,
    TransitStopOnRight = 18,
    TransitStopInLane = 19,
    SharedWithTrackedVehicle = 20,
    SafeIsland = 21,
    LowCurbsPresent = 22,
    RumbleStripPresent = 23,
    AudibleSignalingPresent = 24,
    AdaptiveTimingPresent = 25,
    RfSignalRequestPresent = 26,
    PartialCurbIntrusion = 27,
    TaperToLeft = 28,
    TaperToRight = 29,
    TaperToCenterLine = 30,
    ParallelParking = 31,
    HeadInParking = 32,
    FreeParking = 33,
    TimeRestrictionsOnParking = 34,
    CostToPark = 35,
    MidBlockCurbPresent = 36,
    UnEvenPavementPresent = 37
}